### ISSUE TITLE
[build] pull requests alter the content of the HTML doc

### ISSUE THREAD

**Issue by nodiscc** [shaarli/api-documentation#17]
https://shaarli.github.io/api-documentation/ currently shows the documentation as proposed in https://github.com/shaarli/api-documentation/pull/16, even though the Pull Request has not been merged.

**Comment by virtualtam** [comment]
I've disabled Travis builds for PRs at https://travis-ci.org/shaarli/api-documentation/settings

[EDIT] and restarted a build on `master`
Note that Travis will still run builds for branches (such as `misc`)

**Comment by nodiscc** [comment]
Thank you

**Comment by ArthurHoaro** [comment]
[Oops.](https://github.com/shaarli/api-documentation/commit/55449c66845a2bb7ab767b592d5369138305723c#diff-60254338249f657a0a83f98258a56bfeR14)
