### ISSUE TITLE
how to edit the wiki?

### ISSUE THREAD

**Issue by mro** [shaarli/api-documentation#5]
#2 is not how I want to do it in the future – I tried a wiki edit but see a lengthy discussion while the according page remains blank.

**Comment by virtualtam** [comment]
Discussing around a PR (whether it contains code or documentation changes) is a sane way for both contributors and maintainers to propose changes to the API definition:
- as a maintainer, I wouldn't want contributors to ninja-change such core elements without _notice, discussion and approval_
- as a contributor / 3rd-party app maintainer / API consumer, you wouldn't want maintainers to ninja-change the API without _notice, discussion and approval_ (c.f. https://github.com/dimtion/Shaarlier/issues/15)

Btw, keep in mind that the present repository has a short life expectancy: once a suitable API has been agreed, development will happen, and the API endpoint documentation will be closely coupled to the actual code.

Focusing on GH wiki limitations (c.f. https://github.com/shaarli/Shaarli/issues/312):
- the doc is stored in an underlying Git repository:
  - every page creation/edition/deletion generates a commit
- yet, it is not manageable through the web UI as a standard repository:
  - commit log
  - static resource addition (c.f. https://github.com/shaarli/Shaarli/pull/482)
  - access management
  - peer review

Ideally, the documentation should be generated from code metadata (file/script headers and docstrings). That is, follow the standard commit, PR & peer review process.

Plenty of projects have switched to this paradigm to benefit from automated, up-to-date doc generation:
- minor edits, fixes, typo corrections are merged quickly
- bigger  or controversial changes lead to peer review, comments, new revisions, etc.
